### ISSUE TITLE
Update to using PDF preview

### ISSUE THREAD

**Issue by BPCP** [deas/contentreich-eml#3]
I have been trying to make this work with version 5.0d by changing the transform to a PDF instead of the swf and am having an embarrassingly hard time of it. This is my first foray into transformers and the documentation for complex transformers is either out of date, very sparse or I'm a bit thick.

I was hoping to just drop a 
content.transformer.complex.Rfc822ToPdf.pipeline=RFC822|txt|*|pdf
into alfresco.global.properties and be good to go.
I get a a too few parameters error.

Any help would be greatly appreciated. Loved this in 4

**Comment by deas** [comment]
I really like the idea of PDF previews. What  exactly did you like in Alfresco 4 that broke with 5.0.d? Did that pipeline definition ever work for  you? Will have a look into this.

**Comment by BPCP** [comment]
No the pipeline did not work. Slept on it and it looks like
content.transformer.complex.eml.pdf.pipeline=RFC822|html|OpenOffice.Html2Pdf
is what I need
5:00 am here and I'm scrounging around home for an eml file to test with.

**Comment by BPCP** [comment]
looks like adding the
content.transformer.complex.eml.pdf.pipeline=RFC822|html|OpenOffice.Html2Pdf

fixes the preview wonderfully

I wonder how hard it would be to add into the preview the header
information (to: from: etc) That would make it very nice to print out of
the pdf and have all that info at the top of the page.

**Comment by deas** [comment]
Nice to know the other pipeline works. Adding headers should be easy (and work with swf just as well). And I think it also makes sense, because getting the important headers on a printed email is what you would expect. If  we do this, we should remove those headers from above the preview, so we do not have them twice (or even three times) on the detail page.

**Comment by deas** [comment]
The PDF preview is awesome, @BPCP ! Thanks. I think the extension should use it by default. I'll have a look into adding the headers to the pdf.

Thanks

**Comment by iwkse** [comment]
Hi,
now really connected with this extension but a related issue..maybe you can give me a hint about that.
I have a custom mimetype which is basically HTML and I want that OpenOffice transforms it as this is HTML. I still didn't find a way to say to Alfresco that, to process newMimetype as of HTML type. I'm studying the sources of this extension to find hints.
Also do you have idea where content.transformer.OpenOffice.Html2Pdf comes from? I've grepped in the sources but I couldn't find any refers other than transforms.properties.
Sorry of the little bit [OT], feel free to delete this message if I exaggerated :-)

Regards

**Comment by drisschelouati** [comment]
Hi,

iam a bit confused, this addon is so awesome that i was happy to read there is now a fix for 5.0d. Well, after deploying the jars with the modules deploy console and adding 
`content.transformer.complex.eml.pdf.pipeline=RFC822|html|OpenOffice.Html2Pdf`
to alfresco-global.properties, the preview still fails to load (failed to load pdf content). What am i missing?

Thanks!

**Comment by BPCP** [comment]
@drisschelouati you want to check the transformation first by setting up a rule or using a script to do a straight conversion to PDF. It is sometimes hard to get a preview to generate once it has failed, it the transform works you could try replacing the file to give it a fresh try. Or run create thumbnail script against it.

As an aside I ended up creating an add-on to use wkhtml.exe to do the HTML to PDF conversion and it does a much better job of retaining formatting. https://github.com/BPCP/Alfresco-wkhtml2pdf

**Comment by carbon11** [comment]
The above discussion has been very useful since the pdf2swf transformation seems to have disappeared in Alfresco 5.1 (at least in the CE 201602 aka 5.1.e). Using the contentreich-eml jars, I have the following error (in alfresco.log):
`Cannot create dynamic transformer transformer.complex.Rfc822ToSwf as sub transformers could not be found or created ("RFC822|html|*|pdf|Pdf2swf").`

I could not find any trace of pdf2swf. I then added the following line (based on the above comments) in alfresco-global.properties (overriding the property embedded in the software:
`content.transformer.complex.Rfc822ToSwf.pipeline=RFC822|html|OpenOffice.Html2Pdf`
A little ugly but it works like a charm (but formatting could be improved as mentioned above).
